language: node_js
node_js:
  - "8"

before_script:
  - yarn install

jobs:
  include:
    - stage: "Lint"
      script: yarn lint

    - stage: "Release"
      if: branch = release and type = push
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release --branch release
